spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:6446/dev_co
    username: census_user
    password: ENC(1dIyech+VYkMc0YVMTqesreLilPSPD+3)  

eureka:
  client:
    service-url:
      defaultZone: http://10.251.48.21:8761/eureka/,http://10.251.48.22:8761/eureka/

